const $=s=>document.querySelector(s),canvas=$('#canvas'),ctx=canvas.getContext('2d');
let bg=null,textX=640,textY=120,deferredPrompt=null;
function draw(){ctx.clearRect(0,0,1280,720);ctx.fillStyle='#1e293b';ctx.fillRect(0,0,1280,720);if(bg){const r=Math.max(1280/bg.width,720/bg.height),w=bg.width*r,h=bg.height*r;ctx.drawImage(bg,(1280-w)/2,(720-h)/2,w,h)}const t=$('#titleText').value.trim();if(t){const fs=+$('#fontSize').value;ctx.font='900 '+fs+'px Arial,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';ctx.strokeStyle=$('#strokeColor').value;ctx.lineWidth=Math.max(8,fs/9);ctx.strokeText(t,textX,textY);ctx.fillStyle=$('#textColor').value;ctx.fillText(t,textX,textY)}}
function loadImage(src,cors=false){return new Promise((res,rej)=>{const i=new Image();if(cors)i.crossOrigin='anonymous';i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function aiUrl(p,seed){return 'https://image.pollinations.ai/prompt/'+encodeURIComponent(p)+'?width=1280&height=720&seed='+seed+'&nologo=true&safe=true'}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function makeVariant(box,full,seed,n){const c=document.createElement('div');c.className='card';c.innerHTML='<div style="aspect-ratio:16/9;display:grid;place-items:center;padding:20px;color:#cbd5e1;text-align:center">⏳ Generuję wersję '+n+'…</div><span>Wersja '+n+'</span>';box.appendChild(c);const url=aiUrl(full,seed);try{const im=await loadImage(url,true);c.innerHTML='';im.alt='Wersja '+n;im.style.cssText='display:block;width:100%;aspect-ratio:16/9;object-fit:cover';c.appendChild(im);const s=document.createElement('span');s.textContent='Wersja '+n+' — dotknij, aby edytować';c.appendChild(s);c.onclick=()=>{bg=im;draw();document.querySelector('.editor').scrollIntoView({behavior:'smooth'})};return true}catch(e){c.innerHTML='<div style="aspect-ratio:16/9;display:grid;place-items:center;padding:20px;color:#fca5a5;text-align:center">Nie udało się wygenerować tej wersji.<br>Spróbuj ponownie.</div><span>Wersja '+n+'</span>';return false}}
$('#generate').onclick=async()=>{const p=$('#prompt').value.trim();if(!p)return alert('Najpierw wpisz opis miniatury.');const full=p+', '+$('#style').value+' style, '+$('#category').value+' YouTube thumbnail background, 16:9 composition, strong focal subject, room for large title, no text, no watermark';const box=$('#variants');box.innerHTML='';const btn=$('#generate');btn.disabled=true;const base=Math.floor(Math.random()*900000)+10000;let ok=0;for(let n=1;n<=3;n++){ $('#status').textContent='Generuję wersję '+n+' z 3…';ok+=(await makeVariant(box,full,base+(n-1)*7919,n))?1:0;if(n<3)await sleep(6500)}$('#status').textContent=ok===3?'Gotowe — wybierz jedną z trzech wersji.':'Gotowe '+ok+'/3. Darmowy generator ma ograniczenie szybkości — możesz nacisnąć GENERUJ ponownie.';btn.disabled=false};
$('#upload').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{bg=await loadImage(r.result);draw()};r.readAsDataURL(f)};
['titleText','textColor','strokeColor','fontSize'].forEach(id=>$('#'+id).oninput=draw);
$('#moveLeft').onclick=()=>{textX-=30;draw()};$('#moveRight').onclick=()=>{textX+=30;draw()};$('#moveUp').onclick=()=>{textY-=25;draw()};$('#moveDown').onclick=()=>{textY+=25;draw()};
$('#download').onclick=()=>{draw();const a=document.createElement('a');a.download='youtube-thumbnail.png';a.href=canvas.toDataURL('image/png');a.click()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');draw();