const $=s=>document.querySelector(s),canvas=$('#canvas'),ctx=canvas.getContext('2d');
let bg=null,textX=640,textY=120,deferredPrompt=null,stickers=[],selected=-1,history=[],drag=null;
function snapshot(){history.push(JSON.stringify({textX,textY,stickers}));if(history.length>20)history.shift()}
function draw(){ctx.clearRect(0,0,1280,720);ctx.fillStyle='#1e293b';ctx.fillRect(0,0,1280,720);if(bg){const r=Math.max(1280/bg.width,720/bg.height),w=bg.width*r,h=bg.height*r;ctx.drawImage(bg,(1280-w)/2,(720-h)/2,w,h)}const t=$('#titleText').value.trim();if(t){const fs=+$('#fontSize').value;ctx.font='900 '+fs+'px Arial,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';const eff=$('#textEffect')?$('#textEffect').value:'outline';ctx.shadowColor=eff==='glow'?$('#textColor').value:'#000';ctx.shadowBlur=eff==='glow'?28:eff==='shadow'?16:0;ctx.shadowOffsetX=eff==='shadow'?8:0;ctx.shadowOffsetY=eff==='shadow'?8:0;ctx.strokeStyle=$('#strokeColor').value;ctx.lineWidth=Math.max(8,fs/9);ctx.strokeText(t,textX,textY);ctx.fillStyle=$('#textColor').value;ctx.fillText(t,textX,textY);ctx.shadowBlur=0;ctx.shadowOffsetX=ctx.shadowOffsetY=0}stickers.forEach((s,i)=>{ctx.font=(s.size||90)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(s.char,s.x,s.y);if(i===selected){ctx.strokeStyle='#a78bfa';ctx.lineWidth=5;ctx.strokeRect(s.x-(s.size||90)*.65,s.y-(s.size||90)*.65,(s.size||90)*1.3,(s.size||90)*1.3)}})}
function loadImage(src,cors=false){return new Promise((res,rej)=>{const i=new Image();if(cors)i.crossOrigin='anonymous';i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function aiUrl(p,seed){return 'https://image.pollinations.ai/prompt/'+encodeURIComponent(p)+'?width=1280&height=720&seed='+seed+'&nologo=true&safe=true'}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function makeVariant(box,full,seed,n){const c=document.createElement('div');c.className='card';c.innerHTML='<div style="aspect-ratio:16/9;display:grid;place-items:center;padding:20px;color:#cbd5e1;text-align:center">⏳ Generuję wersję '+n+'…</div><span>Wersja '+n+'</span>';box.appendChild(c);const url=aiUrl(full,seed);try{const im=await loadImage(url,true);c.innerHTML='';im.alt='Wersja '+n;im.style.cssText='display:block;width:100%;aspect-ratio:16/9;object-fit:cover';c.appendChild(im);const s=document.createElement('span');s.textContent='Wersja '+n+' — dotknij, aby edytować';c.appendChild(s);c.onclick=()=>{bg=im;draw();document.querySelector('.editor').scrollIntoView({behavior:'smooth'})};return true}catch(e){c.innerHTML='<div style="aspect-ratio:16/9;display:grid;place-items:center;padding:20px;color:#fca5a5;text-align:center">Nie udało się wygenerować tej wersji.<br>Spróbuj ponownie.</div><span>Wersja '+n+'</span>';return false}}
$('#generate').onclick=async()=>{const p=$('#prompt').value.trim();if(!p)return alert('Najpierw wpisz opis miniatury.');const full=p+', '+$('#style').value+' style, '+$('#category').value+' YouTube thumbnail background, 16:9 composition, strong focal subject, room for large title, no text, no watermark';const box=$('#variants');box.innerHTML='';const btn=$('#generate');btn.disabled=true;const base=Math.floor(Math.random()*900000)+10000;let ok=0;for(let n=1;n<=3;n++){ $('#status').textContent='Generuję wersję '+n+' z 3…';ok+=(await makeVariant(box,full,base+(n-1)*7919,n))?1:0;if(n<3)await sleep(6500)}$('#status').textContent=ok===3?'Gotowe — wybierz jedną z trzech wersji.':'Gotowe '+ok+'/3. Darmowy generator ma ograniczenie szybkości — możesz nacisnąć GENERUJ ponownie.';btn.disabled=false};
$('#upload').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{bg=await loadImage(r.result);draw()};r.readAsDataURL(f)};
['titleText','textColor','strokeColor','fontSize','textEffect'].forEach(id=>$('#'+id).oninput=draw);
document.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>{snapshot();stickers.push({char:b.dataset.sticker,x:640,y:360,size:100});selected=stickers.length-1;draw()});
$('#horseMode').onclick=()=>{snapshot();stickers.push({char:'🐴',x:1080,y:520,size:120},{char:'🏆',x:190,y:540,size:100});selected=stickers.length-1;draw()};
$('#surprise').onclick=()=>{snapshot();const es=['outline','shadow','glow'],cs=['#ffffff','#ffff00','#00ffff','#ff69b4'];$('#textEffect').value=es[Math.floor(Math.random()*es.length)];$('#textColor').value=cs[Math.floor(Math.random()*cs.length)];$('#fontSize').value=70+Math.floor(Math.random()*50);draw()};
$('#undo').onclick=()=>{if(!history.length)return;const s=JSON.parse(history.pop());textX=s.textX;textY=s.textY;stickers=s.stickers;selected=-1;draw()};
function point(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*1280/r.width,y:(p.clientY-r.top)*720/r.height}}
canvas.addEventListener('pointerdown',e=>{const p=point(e);selected=-1;for(let i=stickers.length-1;i>=0;i--){const s=stickers[i],z=s.size||90;if(Math.abs(p.x-s.x)<z*.8&&Math.abs(p.y-s.y)<z*.8){selected=i;break}}snapshot();drag=selected>=0?'sticker':'text';canvas.setPointerCapture?.(e.pointerId);draw()});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e);if(drag==='sticker'&&selected>=0){stickers[selected].x=p.x;stickers[selected].y=p.y}else{textX=p.x;textY=p.y}draw()});
canvas.addEventListener('pointerup',()=>drag=null);
function applyStyle(name){snapshot();if(name==='viral'){ $('#titleText').value='WOW!';$('#textColor').value='#ffff00';$('#strokeColor').value='#000000';$('#fontSize').value=125;$('#textEffect').value='shadow'}if(name==='cute'){ $('#textColor').value='#ff69b4';$('#strokeColor').value='#ffffff';$('#fontSize').value=95;$('#textEffect').value='glow'}if(name==='drama'){ $('#textColor').value='#ff3b30';$('#strokeColor').value='#000000';$('#fontSize').value=120;$('#textEffect').value='shadow'}if(name==='music'){ $('#textColor').value='#00ffff';$('#strokeColor').value='#4c1d95';$('#fontSize').value=105;$('#textEffect').value='glow';stickers.push({char:'🎵',x:1080,y:520,size:110})}draw()}
$('#viralStyle').onclick=()=>applyStyle('viral');$('#cuteStyle').onclick=()=>applyStyle('cute');$('#dramaStyle').onclick=()=>applyStyle('drama');$('#musicStyle').onclick=()=>applyStyle('music');
$('#moveLeft').onclick=()=>{textX-=30;draw()};$('#moveRight').onclick=()=>{textX+=30;draw()};$('#moveUp').onclick=()=>{textY-=25;draw()};$('#moveDown').onclick=()=>{textY+=25;draw()};
$('#download').onclick=()=>{draw();const a=document.createElement('a');a.download='youtube-thumbnail.png';a.href=canvas.toDataURL('image/png');a.click()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');draw();